/**
 * SPEC-20260408-001: Docker Compose Architecture Alignment
 * Test file generated by Reva (SpecSafe Test Engineer)
 *
 * Covers: REQ-A01 through REQ-A09
 * All tests start as `it(...)` per SpecSafe convention.
 * Integration-only scenarios use `it.todo('MANUAL: ...')`.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { parse as parseYaml } from 'yaml';
import { resolve } from 'path';

const PROJECT_DIR = resolve(__dirname, '../../');
const COMPOSE_PATH = resolve(PROJECT_DIR, 'docker-compose.yml');
const OVERRIDE_PATH = resolve(PROJECT_DIR, 'docker-compose.override.yml');
const CADDYFILE_PATH = resolve(PROJECT_DIR, 'Caddyfile');
const ENV_EXAMPLE_PATH = resolve(PROJECT_DIR, '.env.example');
const COMPOSE_CMD = 'docker compose -f docker-compose.yml';
const runManualInfraTests = process.env.RUN_MANUAL_INFRA_TESTS === '1';
const liveInfraIt = runManualInfraTests ? it : it.skip;

function loadCompose(): Record<string, any> {
  const raw = readFileSync(COMPOSE_PATH, 'utf-8');
  return parseYaml(raw);
}

function loadOverride(): Record<string, any> {
  const raw = readFileSync(OVERRIDE_PATH, 'utf-8');
  return parseYaml(raw);
}

function readCaddyfile(): string {
  return readFileSync(CADDYFILE_PATH, 'utf-8');
}

function readEnvExample(): string {
  return readFileSync(ENV_EXAMPLE_PATH, 'utf-8');
}

// Helper: get network names for a service (handles array or object format)
function getServiceNetworks(service: Record<string, any>): string[] {
  const nets = service?.networks;
  if (!nets) return [];
  if (Array.isArray(nets)) return nets;
  if (typeof nets === 'object') return Object.keys(nets);
  return [];
}

// =============================================================================
// REQ-A01: Dual Network Segmentation
// =============================================================================
describe('REQ-A01: Dual Network Segmentation', () => {
  it('T-A01: networks section defines exactly 2 networks (app, langfuse)', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN inspected
    // THEN it defines exactly two networks: app and langfuse
    const compose = loadCompose();
    const networkNames = Object.keys(compose.networks || {});
    expect(networkNames).toHaveLength(2);
    expect(networkNames).toContain('app');
    expect(networkNames).toContain('langfuse');
  });

  it('T-A02: app network has driver: bridge', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN the app network is inspected
    // THEN its driver is bridge
    const compose = loadCompose();
    expect(compose.networks.app.driver).toBe('bridge');
  });

  it('T-A03: langfuse network has driver: bridge', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN the langfuse network is inspected
    // THEN its driver is bridge
    const compose = loadCompose();
    expect(compose.networks.langfuse.driver).toBe('bridge');
  });

  it('T-A04: frontend service networks contains only app', () => {
    // GIVEN service frontend
    // WHEN its network configuration is inspected
    // THEN it is attached only to the app network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.frontend);
    expect(nets).toEqual(['app']);
  });

  it('T-A05: libsql service networks contains only app', () => {
    // GIVEN service libsql
    // WHEN its network configuration is inspected
    // THEN it is attached only to the app network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.libsql);
    expect(nets).toEqual(['app']);
  });

  it('T-A06: langfuse-web networks contains only langfuse', () => {
    // GIVEN service langfuse-web
    // WHEN its network configuration is inspected
    // THEN it is attached only to the langfuse network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services['langfuse-web']);
    expect(nets).toEqual(['langfuse']);
  });

  it('T-A07: langfuse-worker networks contains only langfuse', () => {
    // GIVEN service langfuse-worker
    // WHEN its network configuration is inspected
    // THEN it is attached only to the langfuse network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services['langfuse-worker']);
    expect(nets).toEqual(['langfuse']);
  });

  it('T-A08: clickhouse, redis, minio, langfuse-postgres networks contain only langfuse', () => {
    // GIVEN services clickhouse, redis, minio, langfuse-postgres
    // WHEN their network configuration is inspected
    // THEN each is attached only to the langfuse network
    const compose = loadCompose();
    const langfuseOnlyServices = ['clickhouse', 'redis', 'minio', 'langfuse-postgres'];
    for (const svc of langfuseOnlyServices) {
      const nets = getServiceNetworks(compose.services[svc]);
      expect(nets, `${svc} should only be on langfuse network`).toEqual(['langfuse']);
    }
  });

  it('T-A01-NEG: old triage network does NOT exist', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN inspected
    // THEN there is no network named triage
    const compose = loadCompose();
    const networkNames = Object.keys(compose.networks || {});
    expect(networkNames).not.toContain('triage');
  });

  liveInfraIt('MANUAL: network isolation — app-only service cannot resolve langfuse-only hostname', () => {
    // GIVEN the frontend container is on the app network only
    // WHEN it tries to resolve a langfuse-only hostname (e.g. clickhouse)
    // THEN DNS resolution should fail
    try {
      execSync(
        `${COMPOSE_CMD} exec -T frontend nslookup clickhouse 2>&1`,
        { cwd: PROJECT_DIR, timeout: 30_000 }
      );
      // If nslookup succeeds, the test should fail
      expect.fail('frontend should NOT be able to resolve clickhouse (langfuse-only network)');
    } catch (err: any) {
      // nslookup failure is expected — non-zero exit code
      expect(err.status).not.toBe(0);
    }
  });
});

// =============================================================================
// REQ-A02: Runtime Dual-Network Membership
// =============================================================================
describe('REQ-A02: Runtime Dual-Network Membership', () => {
  it('T-A09: runtime networks list contains both app and langfuse', () => {
    // GIVEN the runtime service definition
    // WHEN its networks list is inspected
    // THEN it includes both app and langfuse
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.runtime);
    expect(nets).toContain('app');
    expect(nets).toContain('langfuse');
  });

  it('T-A10: runtime networks list has exactly 2 entries', () => {
    // GIVEN the runtime service definition
    // WHEN its networks list is inspected
    // THEN it has exactly 2 entries
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.runtime);
    expect(nets).toHaveLength(2);
  });

  liveInfraIt('MANUAL: runtime resolves both libsql (app) and langfuse-web (langfuse) hostnames', () => {
    // GIVEN the runtime container is on both app and langfuse networks
    // WHEN it tries to resolve hostnames from both networks
    // THEN both should succeed
    const libsqlResult = execSync(
      `${COMPOSE_CMD} exec -T runtime nslookup libsql 2>&1 || true`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(libsqlResult).toMatch(/Address/i);

    const langfuseResult = execSync(
      `${COMPOSE_CMD} exec -T runtime nslookup langfuse-web 2>&1 || true`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(langfuseResult).toMatch(/Address/i);
  });

  liveInfraIt('MANUAL: Caddy proxies to runtime:4111 successfully (both on app network)', () => {
    // GIVEN frontend (Caddy) and runtime are both on the app network
    // WHEN we curl the Caddy proxy endpoint for the API
    // THEN we should get a proxied response from the runtime
    const result = execSync(
      'curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/api/health 2>&1 || true',
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    // Accept 200 (proxy works) or 502 (proxy configured but backend down)
    expect(['200', '502']).toContain(result.trim());
  });
});

// =============================================================================
// REQ-A03: Docker Compose Override for Dev Mode
// =============================================================================
describe('REQ-A03: Docker Compose Override for Dev Mode', () => {
  it('T-A11: docker-compose.override.yml exists', () => {
    // GIVEN the project root
    // WHEN checking for docker-compose.override.yml
    // THEN the file exists
    expect(existsSync(OVERRIDE_PATH)).toBe(true);
  });

  it('T-A12: override defines a vite service', () => {
    // GIVEN the docker-compose.override.yml
    // WHEN its services are inspected
    // THEN a vite service is defined
    const override = loadOverride();
    expect(override.services).toHaveProperty('vite');
  });

  it('T-A13: vite service uses node:22-alpine image', () => {
    // GIVEN the vite service in docker-compose.override.yml
    // WHEN its image is inspected
    // THEN it uses node:22-alpine (or compatible node:22 variant)
    const override = loadOverride();
    const image = override.services.vite.image;
    expect(image).toMatch(/node:22/);
  });

  it('T-A14: vite service exposes port 5173', () => {
    // GIVEN the vite service in docker-compose.override.yml
    // WHEN its ports are inspected
    // THEN port 5173 is exposed
    const override = loadOverride();
    const ports = override.services.vite.ports || [];
    const portStrings = ports.map((p: any) => String(p));
    const has5173 = portStrings.some((p: string) => p.includes('5173'));
    expect(has5173).toBe(true);
  });

  it('T-A15: override sets FRONTEND_MODE=dev for Caddy/frontend', () => {
    // GIVEN the docker-compose.override.yml
    // WHEN the frontend service environment is inspected
    // THEN FRONTEND_MODE is set to dev
    const override = loadOverride();
    const frontendEnv = override.services?.frontend?.environment;
    if (Array.isArray(frontendEnv)) {
      expect(frontendEnv).toContain('FRONTEND_MODE=dev');
    } else if (typeof frontendEnv === 'object' && frontendEnv !== null) {
      expect(frontendEnv.FRONTEND_MODE).toBe('dev');
    } else {
      // Check if it's set on another service that controls Caddy
      expect(frontendEnv).toBeDefined();
    }
  });

  it('T-A16: override mounts source volumes for vite', () => {
    // GIVEN the vite service in docker-compose.override.yml
    // WHEN its volumes are inspected
    // THEN source code volumes are mounted
    const override = loadOverride();
    const volumes = override.services.vite.volumes || [];
    expect(volumes.length).toBeGreaterThan(0);
  });

  it('T-A17: override changes runtime command to mastra dev on port 4111', () => {
    // GIVEN the runtime service override in docker-compose.override.yml
    // WHEN its command is inspected
    // THEN it runs mastra dev with the explicit runtime port
    const override = loadOverride();
    const cmd = override.services?.runtime?.command;
    const cmdStr = Array.isArray(cmd) ? cmd.join(' ') : String(cmd || '');
    expect(cmdStr).toMatch(/mastra\s+dev/i);
    expect(cmdStr).toMatch(/--port\s+4111/);
  });

  it('T-A03-NEG: base compose has no vite service (prod mode)', () => {
    // GIVEN the base docker-compose.yml (without override)
    // WHEN services are inspected
    // THEN no vite service exists
    const compose = loadCompose();
    expect(compose.services).not.toHaveProperty('vite');
  });

  liveInfraIt('MANUAL: docker compose up auto-loads override and starts vite with HMR', () => {
    // GIVEN docker-compose.override.yml exists alongside docker-compose.yml
    // WHEN `docker compose config --services` is run (includes override by default)
    // THEN the vite service should appear in the service list
    const output = execSync(
      'docker compose config --services 2>&1',
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(output).toContain('vite');
  });

  liveInfraIt('MANUAL: docker compose -f docker-compose.yml up skips override', () => {
    // GIVEN only docker-compose.yml is specified (no override)
    // WHEN `docker compose -f docker-compose.yml config --services` is run
    // THEN the vite service should NOT appear
    const output = execSync(
      `${COMPOSE_CMD} config --services 2>&1`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(output).not.toContain('vite');
  });
});

// =============================================================================
// REQ-A04: Caddyfile Environment Variable Switching
// =============================================================================
describe('REQ-A04: Caddyfile Environment Variable Switching', () => {
  it('T-A18: Caddyfile contains (static-frontend) snippet', () => {
    // GIVEN the Caddyfile
    // WHEN inspected
    // THEN it contains a (static-frontend) snippet definition
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/\(static-frontend\)/);
  });

  it('T-A19: Caddyfile contains (dev-frontend) snippet', () => {
    // GIVEN the Caddyfile
    // WHEN inspected
    // THEN it contains a (dev-frontend) snippet definition
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/\(dev-frontend\)/);
  });

  it('T-A20: static-frontend snippet includes root, try_files, file_server', () => {
    // GIVEN the static-frontend snippet in the Caddyfile
    // WHEN its content is inspected
    // THEN it contains root, try_files, and file_server directives
    const caddy = readCaddyfile();
    // Extract the full static-frontend snippet block (greedy enough to capture nested blocks)
    const staticStart = caddy.indexOf('(static-frontend)');
    const braceStart = caddy.indexOf('{', staticStart);
    let depth = 0;
    let braceEnd = braceStart;
    for (let i = braceStart; i < caddy.length; i++) {
      if (caddy[i] === '{') depth++;
      if (caddy[i] === '}') depth--;
      if (depth === 0) { braceEnd = i; break; }
    }
    const snippet = caddy.substring(braceStart + 1, braceEnd);
    expect(snippet).toMatch(/root/);
    expect(snippet).toMatch(/try_files/);
    expect(snippet).toMatch(/file_server/);
  });

  it('T-A21: dev-frontend snippet has reverse_proxy to vite:5173', () => {
    // GIVEN the dev-frontend snippet in the Caddyfile
    // WHEN its content is inspected
    // THEN it contains reverse_proxy to vite:5173
    const caddy = readCaddyfile();
    const devMatch = caddy.match(/\(dev-frontend\)[\s\S]*?\{([\s\S]*?)\}/);
    const snippet = devMatch ? devMatch[1] : '';
    expect(snippet).toMatch(/reverse_proxy.*vite:5173/);
  });

  it('T-A22: Caddyfile uses import {$FRONTEND_MODE:static}-frontend', () => {
    // GIVEN the Caddyfile
    // WHEN inspected
    // THEN it contains the dynamic import with default static
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/import\s+\{\$FRONTEND_MODE:static\}-frontend/);
  });

  it('T-A04-DEFAULT: default is static when FRONTEND_MODE is unset', () => {
    // GIVEN the Caddyfile import directive
    // WHEN FRONTEND_MODE is not set
    // THEN the default value in the import is "static"
    const caddy = readCaddyfile();
    const importMatch = caddy.match(/import\s+\{\$FRONTEND_MODE:(\w+)\}-frontend/);
    expect(importMatch).not.toBeNull();
    expect(importMatch![1]).toBe('static');
  });

  liveInfraIt('MANUAL: Caddy starts in prod mode when FRONTEND_MODE is unset', () => {
    // GIVEN docker compose is running with -f docker-compose.yml (no override)
    // WHEN the frontend container is checked
    // THEN Caddy should be serving static files (prod mode)
    const result = execSync(
      'curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/ 2>&1 || true',
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    // In prod mode, Caddy serves static files — expect 200 or similar
    const code = parseInt(result.trim(), 10);
    expect(code).toBeGreaterThan(0);
    expect(code).toBeLessThan(600);
  });

  liveInfraIt('MANUAL: Caddy proxies to vite:5173 when FRONTEND_MODE=dev', () => {
    // GIVEN the Caddyfile has a dev-frontend snippet with reverse_proxy vite:5173
    // WHEN we read the Caddyfile
    // THEN the dev-frontend snippet should proxy to vite:5173
    // (actual runtime test requires vite container — we validate config)
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/reverse_proxy.*vite:5173/);
  });
});

// =============================================================================
// REQ-A05: Frontend Runtime Config.json
// =============================================================================
describe('REQ-A05: Frontend Runtime Config.json', () => {
  it('T-A23: Caddyfile serves /config.json before SPA fallback', () => {
    // GIVEN the Caddyfile
    // WHEN the handle directives are inspected
    // THEN /config.json is handled before the SPA try_files catch-all
    const caddy = readCaddyfile();
    // config.json should appear (either as a handle block or file_server path)
    expect(caddy).toMatch(/config\.json/);

    // Verify config.json handling appears before SPA fallback (try_files)
    const configPos = caddy.indexOf('config.json');
    const tryFilesPos = caddy.indexOf('try_files');
    if (tryFilesPos !== -1) {
      expect(configPos).toBeLessThan(tryFilesPos);
    }
  });

  it('T-A24: frontend service has config.json volume mount', () => {
    // GIVEN docker-compose.yml
    // WHEN the frontend service volumes are inspected
    // THEN config.json is volume-mounted (not baked into image)
    const compose = loadCompose();
    const volumes = compose.services.frontend.volumes || [];
    const volumeStrings = volumes.map((v: any) => String(v));
    const hasConfigMount = volumeStrings.some((v: string) => v.includes('config.json'));
    expect(hasConfigMount).toBe(true);
  });

  liveInfraIt('MANUAL: GET /config.json returns JSON in prod mode without SPA fallback', () => {
    // GIVEN frontend (Caddy) is running in prod mode
    // WHEN we request /config.json
    // THEN it returns valid JSON (not the SPA index.html)
    const result = execSync(
      'curl -s http://localhost:3001/config.json 2>&1 || true',
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    // Should be valid JSON, not HTML
    expect(result.trim()).not.toMatch(/^<!DOCTYPE/i);
    expect(() => JSON.parse(result.trim())).not.toThrow();
  });

  liveInfraIt('MANUAL: in dev mode, Vite serves /config.json from public directory', () => {
    // Validate that config.json exists in the project for Vite to serve from public/
    const configPath = resolve(PROJECT_DIR, 'config.json');
    expect(existsSync(configPath)).toBe(true);
    const content = readFileSync(configPath, 'utf-8');
    expect(() => JSON.parse(content)).not.toThrow();
  });
});

// =============================================================================
// REQ-A06: ClickHouse Password Configuration
// =============================================================================
describe('REQ-A06: ClickHouse Password Configuration', () => {
  it('T-A25: clickhouse service has CLICKHOUSE_PASSWORD in environment', () => {
    // GIVEN the clickhouse service definition
    // WHEN its environment section is inspected
    // THEN CLICKHOUSE_PASSWORD is set
    const compose = loadCompose();
    const env = compose.services.clickhouse.environment;
    if (Array.isArray(env)) {
      const hasPassword = env.some((e: string) => e.startsWith('CLICKHOUSE_PASSWORD'));
      expect(hasPassword).toBe(true);
    } else {
      expect(env).toHaveProperty('CLICKHOUSE_PASSWORD');
    }
  });

  it('T-A26: .env.example has CLICKHOUSE_PASSWORD=CHANGEME', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains CLICKHOUSE_PASSWORD=CHANGEME
    const envFile = readEnvExample();
    expect(envFile).toMatch(/CLICKHOUSE_PASSWORD=CHANGEME/);
  });

  it('T-A06-SHARED: langfuse services reference same CLICKHOUSE_PASSWORD variable', () => {
    // GIVEN langfuse-web and langfuse-worker services
    // WHEN their CLICKHOUSE_PASSWORD env var is inspected
    // THEN it references the same variable as clickhouse service
    const compose = loadCompose();
    const services = ['langfuse-web', 'langfuse-worker'];
    for (const svc of services) {
      const env = compose.services[svc]?.environment;
      if (Array.isArray(env)) {
        const hasPassword = env.some((e: string) => e.includes('CLICKHOUSE_PASSWORD'));
        expect(hasPassword, `${svc} should reference CLICKHOUSE_PASSWORD`).toBe(true);
      } else if (typeof env === 'object' && env !== null) {
        // CLICKHOUSE_PASSWORD may be in the YAML anchor (<<) or directly on the env object
        const anchor = env['<<'] || {};
        const hasPassword = env.hasOwnProperty('CLICKHOUSE_PASSWORD') || anchor.hasOwnProperty('CLICKHOUSE_PASSWORD');
        expect(hasPassword, `${svc} should have CLICKHOUSE_PASSWORD (direct or via anchor)`).toBe(true);
      }
    }
  });

  liveInfraIt('MANUAL: ClickHouse starts with password, Langfuse connects successfully', () => {
    // GIVEN the clickhouse container is running
    // WHEN we check its health status
    // THEN it should be healthy
    const result = execSync(
      `docker inspect --format '{{.State.Health.Status}}' triage-feature-linear-and-resend-integration-clickhouse-1 2>&1 || true`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(result.trim()).toBe('healthy');
  });
});

// =============================================================================
// REQ-A07: MinIO Health Check Alignment
// =============================================================================
describe('REQ-A07: MinIO Health Check Alignment', () => {
  it('T-A27: minio healthcheck uses mc ready local or curl fallback', () => {
    // GIVEN the minio service definition
    // WHEN its healthcheck is inspected
    // THEN it uses "mc ready local" or a curl fallback
    const compose = loadCompose();
    const healthcheck = compose.services.minio.healthcheck;
    expect(healthcheck).toBeDefined();
    const testCmd = Array.isArray(healthcheck.test)
      ? healthcheck.test.join(' ')
      : String(healthcheck.test || '');
    const usesMc = testCmd.includes('mc ready local');
    const usesCurl = testCmd.includes('curl') && testCmd.includes('minio/health');
    expect(usesMc || usesCurl, 'healthcheck should use mc ready local or curl fallback').toBe(true);
  });

  liveInfraIt('MANUAL: MinIO starts, healthcheck passes, dependents can connect', () => {
    // GIVEN the minio container is running
    // WHEN we check its health status
    // THEN it should be healthy
    const result = execSync(
      `docker inspect --format '{{.State.Health.Status}}' triage-feature-linear-and-resend-integration-minio-1 2>&1 || true`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(result.trim()).toBe('healthy');
  });
});

// =============================================================================
// REQ-A08: Redis Health Check Auth Warning Suppression
// =============================================================================
describe('REQ-A08: Redis Health Check Auth Warning Suppression', () => {
  it('T-A28: redis healthcheck includes --no-auth-warning', () => {
    // GIVEN the redis service healthcheck
    // WHEN inspected
    // THEN it includes the --no-auth-warning flag
    const compose = loadCompose();
    const healthcheck = compose.services.redis.healthcheck;
    expect(healthcheck).toBeDefined();
    const testCmd = Array.isArray(healthcheck.test)
      ? healthcheck.test.join(' ')
      : String(healthcheck.test || '');
    expect(testCmd).toContain('--no-auth-warning');
  });

  liveInfraIt('MANUAL: redis healthcheck runs without auth warning in logs', () => {
    // GIVEN the redis container is running
    // WHEN we check its health status and recent logs
    // THEN it should be healthy and logs should not contain auth warnings
    const healthResult = execSync(
      `docker inspect --format '{{.State.Health.Status}}' triage-feature-linear-and-resend-integration-redis-1 2>&1 || true`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    expect(healthResult.trim()).toBe('healthy');

    const logs = execSync(
      `${COMPOSE_CMD} logs redis --tail=50 2>&1 || true`,
      { cwd: PROJECT_DIR, timeout: 30_000, encoding: 'utf-8' }
    );
    // Should not have "Warning: Using a password with" auth messages
    expect(logs).not.toMatch(/Warning:.*password.*auth/i);
  });
});

// =============================================================================
// REQ-A09: Environment Variable Updates
// =============================================================================
describe('REQ-A09: Environment Variable Updates', () => {
  it('T-A29: .env.example contains FRONTEND_MODE', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains FRONTEND_MODE
    const envFile = readEnvExample();
    expect(envFile).toMatch(/FRONTEND_MODE/);
  });

  it('T-A30: FRONTEND_MODE default is static', () => {
    // GIVEN .env.example
    // WHEN the FRONTEND_MODE line is inspected
    // THEN its value is static
    const envFile = readEnvExample();
    expect(envFile).toMatch(/FRONTEND_MODE=static/);
  });

  it('T-A31: .env.example has comment explaining FRONTEND_MODE values', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN there is a comment near FRONTEND_MODE explaining valid values (dev/static)
    const envFile = readEnvExample();
    const lines = envFile.split('\n');
    const modeLineIdx = lines.findIndex((l) => l.includes('FRONTEND_MODE'));
    expect(modeLineIdx).toBeGreaterThanOrEqual(0);
    // Check for a comment on the same line or the line before
    const commentOnLine = lines[modeLineIdx].includes('#');
    const commentBefore = modeLineIdx > 0 && lines[modeLineIdx - 1].trim().startsWith('#');
    expect(
      commentOnLine || commentBefore,
      'FRONTEND_MODE should have an explanatory comment'
    ).toBe(true);
  });

  it('T-A32: existing variables are not removed from .env.example', () => {
    // GIVEN .env.example
    // WHEN compared to known existing variables
    // THEN none of the previously existing variables are removed
    const envFile = readEnvExample();
    // Sample of known variables from the base infrastructure (SPEC-20260407-001)
    const knownVars = [
      'REDIS_AUTH',
      'LANGFUSE_SECRET_KEY',
      'NEXTAUTH_SECRET',
      'SALT',
    ];
    for (const varName of knownVars) {
      expect(envFile, `${varName} should still be present`).toContain(varName);
    }
  });

  it('T-A09-CLICKHOUSE: .env.example contains CLICKHOUSE_PASSWORD=CHANGEME', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains CLICKHOUSE_PASSWORD=CHANGEME
    const envFile = readEnvExample();
    expect(envFile).toMatch(/CLICKHOUSE_PASSWORD=CHANGEME/);
  });

  it('T-A33: .env.example contains RESEND_FROM_EMAIL with correct domain', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains RESEND_FROM_EMAIL set to triage@agenticengineering.lat
    const envFile = readEnvExample();
    expect(envFile).toMatch(/RESEND_FROM_EMAIL=triage@agenticengineering\.lat/);
  });
});

// =============================================================================
// REQ-A10: Runtime Service Integration Configuration
// =============================================================================
describe('REQ-A10: Runtime Service Integration Configuration', () => {
  it('T-A34: runtime service depends on libsql with service_healthy', () => {
    // GIVEN the docker-compose.yml
    // WHEN the runtime service depends_on is inspected
    // THEN libsql is listed with condition: service_healthy
    const compose = loadCompose();
    const deps = compose.services.runtime?.depends_on;
    expect(deps).toBeDefined();
    expect(deps?.libsql?.condition).toBe('service_healthy');
  });

  it('T-A35: runtime service uses env_file to load .env', () => {
    // GIVEN the docker-compose.yml
    // WHEN the runtime service env_file is inspected
    // THEN it references .env (which contains LINEAR_API_KEY, RESEND_API_KEY, etc.)
    const compose = loadCompose();
    const envFile = compose.services.runtime?.env_file;
    expect(envFile).toBeDefined();
    const envFileStr = Array.isArray(envFile) ? envFile.join(' ') : String(envFile);
    expect(envFileStr).toContain('.env');
  });

  it('T-A36: runtime service does not hardcode integration API keys in compose', () => {
    // GIVEN the docker-compose.yml
    // WHEN the runtime service environment is inspected
    // THEN LINEAR_API_KEY and RESEND_API_KEY are NOT hardcoded (they come via env_file)
    const compose = loadCompose();
    const env = compose.services.runtime?.environment;
    if (env && typeof env === 'object') {
      expect(env).not.toHaveProperty('LINEAR_API_KEY');
      expect(env).not.toHaveProperty('RESEND_API_KEY');
      expect(env).not.toHaveProperty('RESEND_FROM_EMAIL');
    }
    // If env is undefined, that's fine — keys come from env_file
  });

  it('T-A37: .env.example has LINEAR_API_KEY and RESEND_API_KEY under Integrations section', () => {
    // GIVEN .env.example
    // WHEN the Integrations section is inspected
    // THEN LINEAR_API_KEY and RESEND_API_KEY appear after the Integrations header
    const envFile = readEnvExample();
    const integrationsIdx = envFile.indexOf('# === Integrations ===');
    expect(integrationsIdx).toBeGreaterThanOrEqual(0);
    const afterIntegrations = envFile.substring(integrationsIdx);
    expect(afterIntegrations).toMatch(/LINEAR_API_KEY/);
    expect(afterIntegrations).toMatch(/RESEND_API_KEY/);
    expect(afterIntegrations).toMatch(/RESEND_FROM_EMAIL/);
  });
});
