/**
 * SPEC-20260408-001: Docker Compose Architecture Alignment
 * Test file generated by Reva (SpecSafe Test Engineer)
 *
 * Covers: REQ-A01 through REQ-A09
 * All tests start as `it(...)` per SpecSafe convention.
 * Integration-only scenarios use `it.todo('MANUAL: ...')`.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { parse as parseYaml } from 'yaml';
import { resolve } from 'path';

const COMPOSE_PATH = resolve(__dirname, '../../docker-compose.yml');
const OVERRIDE_PATH = resolve(__dirname, '../../docker-compose.override.yml');
const CADDYFILE_PATH = resolve(__dirname, '../../Caddyfile');
const ENV_EXAMPLE_PATH = resolve(__dirname, '../../.env.example');

function loadCompose(): Record<string, any> {
  const raw = readFileSync(COMPOSE_PATH, 'utf-8');
  return parseYaml(raw);
}

function loadOverride(): Record<string, any> {
  const raw = readFileSync(OVERRIDE_PATH, 'utf-8');
  return parseYaml(raw);
}

function readCaddyfile(): string {
  return readFileSync(CADDYFILE_PATH, 'utf-8');
}

function readEnvExample(): string {
  return readFileSync(ENV_EXAMPLE_PATH, 'utf-8');
}

// Helper: get network names for a service (handles array or object format)
function getServiceNetworks(service: Record<string, any>): string[] {
  const nets = service?.networks;
  if (!nets) return [];
  if (Array.isArray(nets)) return nets;
  if (typeof nets === 'object') return Object.keys(nets);
  return [];
}

// =============================================================================
// REQ-A01: Dual Network Segmentation
// =============================================================================
describe('REQ-A01: Dual Network Segmentation', () => {
  it('T-A01: networks section defines exactly 2 networks (app, langfuse)', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN inspected
    // THEN it defines exactly two networks: app and langfuse
    const compose = loadCompose();
    const networkNames = Object.keys(compose.networks || {});
    expect(networkNames).toHaveLength(2);
    expect(networkNames).toContain('app');
    expect(networkNames).toContain('langfuse');
  });

  it('T-A02: app network has driver: bridge', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN the app network is inspected
    // THEN its driver is bridge
    const compose = loadCompose();
    expect(compose.networks.app.driver).toBe('bridge');
  });

  it('T-A03: langfuse network has driver: bridge', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN the langfuse network is inspected
    // THEN its driver is bridge
    const compose = loadCompose();
    expect(compose.networks.langfuse.driver).toBe('bridge');
  });

  it('T-A04: frontend service networks contains only app', () => {
    // GIVEN service frontend
    // WHEN its network configuration is inspected
    // THEN it is attached only to the app network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.frontend);
    expect(nets).toEqual(['app']);
  });

  it('T-A05: libsql service networks contains only app', () => {
    // GIVEN service libsql
    // WHEN its network configuration is inspected
    // THEN it is attached only to the app network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.libsql);
    expect(nets).toEqual(['app']);
  });

  it('T-A06: langfuse-web networks contains only langfuse', () => {
    // GIVEN service langfuse-web
    // WHEN its network configuration is inspected
    // THEN it is attached only to the langfuse network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services['langfuse-web']);
    expect(nets).toEqual(['langfuse']);
  });

  it('T-A07: langfuse-worker networks contains only langfuse', () => {
    // GIVEN service langfuse-worker
    // WHEN its network configuration is inspected
    // THEN it is attached only to the langfuse network
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services['langfuse-worker']);
    expect(nets).toEqual(['langfuse']);
  });

  it('T-A08: clickhouse, redis, minio, langfuse-postgres networks contain only langfuse', () => {
    // GIVEN services clickhouse, redis, minio, langfuse-postgres
    // WHEN their network configuration is inspected
    // THEN each is attached only to the langfuse network
    const compose = loadCompose();
    const langfuseOnlyServices = ['clickhouse', 'redis', 'minio', 'langfuse-postgres'];
    for (const svc of langfuseOnlyServices) {
      const nets = getServiceNetworks(compose.services[svc]);
      expect(nets, `${svc} should only be on langfuse network`).toEqual(['langfuse']);
    }
  });

  it('T-A01-NEG: old triage network does NOT exist', () => {
    // GIVEN the docker-compose.yml networks section
    // WHEN inspected
    // THEN there is no network named triage
    const compose = loadCompose();
    const networkNames = Object.keys(compose.networks || {});
    expect(networkNames).not.toContain('triage');
  });

  it.todo('MANUAL: network isolation — app-only service cannot resolve langfuse-only hostname');
});

// =============================================================================
// REQ-A02: Runtime Dual-Network Membership
// =============================================================================
describe('REQ-A02: Runtime Dual-Network Membership', () => {
  it('T-A09: runtime networks list contains both app and langfuse', () => {
    // GIVEN the runtime service definition
    // WHEN its networks list is inspected
    // THEN it includes both app and langfuse
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.runtime);
    expect(nets).toContain('app');
    expect(nets).toContain('langfuse');
  });

  it('T-A10: runtime networks list has exactly 2 entries', () => {
    // GIVEN the runtime service definition
    // WHEN its networks list is inspected
    // THEN it has exactly 2 entries
    const compose = loadCompose();
    const nets = getServiceNetworks(compose.services.runtime);
    expect(nets).toHaveLength(2);
  });

  it.todo('MANUAL: runtime resolves both libsql (app) and langfuse-web (langfuse) hostnames');
  it.todo('MANUAL: Caddy proxies to runtime:4111 successfully (both on app network)');
});

// =============================================================================
// REQ-A03: Docker Compose Override for Dev Mode
// =============================================================================
describe('REQ-A03: Docker Compose Override for Dev Mode', () => {
  it('T-A11: docker-compose.override.yml exists', () => {
    // GIVEN the project root
    // WHEN checking for docker-compose.override.yml
    // THEN the file exists
    expect(existsSync(OVERRIDE_PATH)).toBe(true);
  });

  it('T-A12: override defines a vite service', () => {
    // GIVEN the docker-compose.override.yml
    // WHEN its services are inspected
    // THEN a vite service is defined
    const override = loadOverride();
    expect(override.services).toHaveProperty('vite');
  });

  it('T-A13: vite service uses node:22-alpine image', () => {
    // GIVEN the vite service in docker-compose.override.yml
    // WHEN its image is inspected
    // THEN it uses node:22-alpine (or compatible node:22 variant)
    const override = loadOverride();
    const image = override.services.vite.image;
    expect(image).toMatch(/node:22/);
  });

  it('T-A14: vite service exposes port 5173', () => {
    // GIVEN the vite service in docker-compose.override.yml
    // WHEN its ports are inspected
    // THEN port 5173 is exposed
    const override = loadOverride();
    const ports = override.services.vite.ports || [];
    const portStrings = ports.map((p: any) => String(p));
    const has5173 = portStrings.some((p: string) => p.includes('5173'));
    expect(has5173).toBe(true);
  });

  it('T-A15: override sets FRONTEND_MODE=dev for Caddy/frontend', () => {
    // GIVEN the docker-compose.override.yml
    // WHEN the frontend service environment is inspected
    // THEN FRONTEND_MODE is set to dev
    const override = loadOverride();
    const frontendEnv = override.services?.frontend?.environment;
    if (Array.isArray(frontendEnv)) {
      expect(frontendEnv).toContain('FRONTEND_MODE=dev');
    } else if (typeof frontendEnv === 'object' && frontendEnv !== null) {
      expect(frontendEnv.FRONTEND_MODE).toBe('dev');
    } else {
      // Check if it's set on another service that controls Caddy
      expect(frontendEnv).toBeDefined();
    }
  });

  it('T-A16: override mounts source volumes for vite', () => {
    // GIVEN the vite service in docker-compose.override.yml
    // WHEN its volumes are inspected
    // THEN source code volumes are mounted
    const override = loadOverride();
    const volumes = override.services.vite.volumes || [];
    expect(volumes.length).toBeGreaterThan(0);
  });

  it('T-A17: override changes runtime command to tsx --watch', () => {
    // GIVEN the runtime service override in docker-compose.override.yml
    // WHEN its command is inspected
    // THEN it contains tsx --watch (or tsx watch)
    const override = loadOverride();
    const cmd = override.services?.runtime?.command;
    const cmdStr = Array.isArray(cmd) ? cmd.join(' ') : String(cmd || '');
    expect(cmdStr).toMatch(/tsx.*watch/i);
  });

  it('T-A03-NEG: base compose has no vite service (prod mode)', () => {
    // GIVEN the base docker-compose.yml (without override)
    // WHEN services are inspected
    // THEN no vite service exists
    const compose = loadCompose();
    expect(compose.services).not.toHaveProperty('vite');
  });

  it.todo('MANUAL: docker compose up auto-loads override and starts vite with HMR');
  it.todo('MANUAL: docker compose -f docker-compose.yml up skips override');
});

// =============================================================================
// REQ-A04: Caddyfile Environment Variable Switching
// =============================================================================
describe('REQ-A04: Caddyfile Environment Variable Switching', () => {
  it('T-A18: Caddyfile contains (static-frontend) snippet', () => {
    // GIVEN the Caddyfile
    // WHEN inspected
    // THEN it contains a (static-frontend) snippet definition
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/\(static-frontend\)/);
  });

  it('T-A19: Caddyfile contains (dev-frontend) snippet', () => {
    // GIVEN the Caddyfile
    // WHEN inspected
    // THEN it contains a (dev-frontend) snippet definition
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/\(dev-frontend\)/);
  });

  it('T-A20: static-frontend snippet includes root, try_files, file_server', () => {
    // GIVEN the static-frontend snippet in the Caddyfile
    // WHEN its content is inspected
    // THEN it contains root, try_files, and file_server directives
    const caddy = readCaddyfile();
    // Extract the static-frontend snippet block (heuristic: from snippet def to next snippet or closing brace)
    const staticMatch = caddy.match(/\(static-frontend\)[\s\S]*?\{([\s\S]*?)\}/);
    const snippet = staticMatch ? staticMatch[1] : '';
    expect(snippet).toMatch(/root/);
    expect(snippet).toMatch(/try_files/);
    expect(snippet).toMatch(/file_server/);
  });

  it('T-A21: dev-frontend snippet has reverse_proxy to vite:5173', () => {
    // GIVEN the dev-frontend snippet in the Caddyfile
    // WHEN its content is inspected
    // THEN it contains reverse_proxy to vite:5173
    const caddy = readCaddyfile();
    const devMatch = caddy.match(/\(dev-frontend\)[\s\S]*?\{([\s\S]*?)\}/);
    const snippet = devMatch ? devMatch[1] : '';
    expect(snippet).toMatch(/reverse_proxy.*vite:5173/);
  });

  it('T-A22: Caddyfile uses import {$FRONTEND_MODE:static}-frontend', () => {
    // GIVEN the Caddyfile
    // WHEN inspected
    // THEN it contains the dynamic import with default static
    const caddy = readCaddyfile();
    expect(caddy).toMatch(/import\s+\{\$FRONTEND_MODE:static\}-frontend/);
  });

  it('T-A04-DEFAULT: default is static when FRONTEND_MODE is unset', () => {
    // GIVEN the Caddyfile import directive
    // WHEN FRONTEND_MODE is not set
    // THEN the default value in the import is "static"
    const caddy = readCaddyfile();
    const importMatch = caddy.match(/import\s+\{\$FRONTEND_MODE:(\w+)\}-frontend/);
    expect(importMatch).not.toBeNull();
    expect(importMatch![1]).toBe('static');
  });

  it.todo('MANUAL: Caddy starts in prod mode when FRONTEND_MODE is unset');
  it.todo('MANUAL: Caddy proxies to vite:5173 when FRONTEND_MODE=dev');
});

// =============================================================================
// REQ-A05: Frontend Runtime Config.json
// =============================================================================
describe('REQ-A05: Frontend Runtime Config.json', () => {
  it('T-A23: Caddyfile serves /config.json before SPA fallback', () => {
    // GIVEN the Caddyfile
    // WHEN the handle directives are inspected
    // THEN /config.json is handled before the SPA try_files catch-all
    const caddy = readCaddyfile();
    // config.json should appear (either as a handle block or file_server path)
    expect(caddy).toMatch(/config\.json/);

    // Verify config.json handling appears before SPA fallback (try_files)
    const configPos = caddy.indexOf('config.json');
    const tryFilesPos = caddy.indexOf('try_files');
    if (tryFilesPos !== -1) {
      expect(configPos).toBeLessThan(tryFilesPos);
    }
  });

  it('T-A24: frontend service has config.json volume mount', () => {
    // GIVEN docker-compose.yml
    // WHEN the frontend service volumes are inspected
    // THEN config.json is volume-mounted (not baked into image)
    const compose = loadCompose();
    const volumes = compose.services.frontend.volumes || [];
    const volumeStrings = volumes.map((v: any) => String(v));
    const hasConfigMount = volumeStrings.some((v: string) => v.includes('config.json'));
    expect(hasConfigMount).toBe(true);
  });

  it.todo('MANUAL: GET /config.json returns JSON in prod mode without SPA fallback');
  it.todo('MANUAL: in dev mode, Vite serves /config.json from public directory');
});

// =============================================================================
// REQ-A06: ClickHouse Password Configuration
// =============================================================================
describe('REQ-A06: ClickHouse Password Configuration', () => {
  it('T-A25: clickhouse service has CLICKHOUSE_PASSWORD in environment', () => {
    // GIVEN the clickhouse service definition
    // WHEN its environment section is inspected
    // THEN CLICKHOUSE_PASSWORD is set
    const compose = loadCompose();
    const env = compose.services.clickhouse.environment;
    if (Array.isArray(env)) {
      const hasPassword = env.some((e: string) => e.startsWith('CLICKHOUSE_PASSWORD'));
      expect(hasPassword).toBe(true);
    } else {
      expect(env).toHaveProperty('CLICKHOUSE_PASSWORD');
    }
  });

  it('T-A26: .env.example has CLICKHOUSE_PASSWORD=CHANGEME', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains CLICKHOUSE_PASSWORD=CHANGEME
    const envFile = readEnvExample();
    expect(envFile).toMatch(/CLICKHOUSE_PASSWORD=CHANGEME/);
  });

  it('T-A06-SHARED: langfuse services reference same CLICKHOUSE_PASSWORD variable', () => {
    // GIVEN langfuse-web and langfuse-worker services
    // WHEN their CLICKHOUSE_PASSWORD env var is inspected
    // THEN it references the same variable as clickhouse service
    const compose = loadCompose();
    const services = ['langfuse-web', 'langfuse-worker'];
    for (const svc of services) {
      const env = compose.services[svc]?.environment;
      if (Array.isArray(env)) {
        const hasPassword = env.some((e: string) => e.includes('CLICKHOUSE_PASSWORD'));
        expect(hasPassword, `${svc} should reference CLICKHOUSE_PASSWORD`).toBe(true);
      } else if (typeof env === 'object' && env !== null) {
        expect(env, `${svc} should have CLICKHOUSE_PASSWORD`).toHaveProperty('CLICKHOUSE_PASSWORD');
      }
    }
  });

  it.todo('MANUAL: ClickHouse starts with password, Langfuse connects successfully');
});

// =============================================================================
// REQ-A07: MinIO Health Check Alignment
// =============================================================================
describe('REQ-A07: MinIO Health Check Alignment', () => {
  it('T-A27: minio healthcheck uses mc ready local or curl fallback', () => {
    // GIVEN the minio service definition
    // WHEN its healthcheck is inspected
    // THEN it uses "mc ready local" or a curl fallback
    const compose = loadCompose();
    const healthcheck = compose.services.minio.healthcheck;
    expect(healthcheck).toBeDefined();
    const testCmd = Array.isArray(healthcheck.test)
      ? healthcheck.test.join(' ')
      : String(healthcheck.test || '');
    const usesMc = testCmd.includes('mc ready local');
    const usesCurl = testCmd.includes('curl') && testCmd.includes('minio/health');
    expect(usesMc || usesCurl, 'healthcheck should use mc ready local or curl fallback').toBe(true);
  });

  it.todo('MANUAL: MinIO starts, healthcheck passes, dependents can connect');
});

// =============================================================================
// REQ-A08: Redis Health Check Auth Warning Suppression
// =============================================================================
describe('REQ-A08: Redis Health Check Auth Warning Suppression', () => {
  it('T-A28: redis healthcheck includes --no-auth-warning', () => {
    // GIVEN the redis service healthcheck
    // WHEN inspected
    // THEN it includes the --no-auth-warning flag
    const compose = loadCompose();
    const healthcheck = compose.services.redis.healthcheck;
    expect(healthcheck).toBeDefined();
    const testCmd = Array.isArray(healthcheck.test)
      ? healthcheck.test.join(' ')
      : String(healthcheck.test || '');
    expect(testCmd).toContain('--no-auth-warning');
  });

  it.todo('MANUAL: redis healthcheck runs without auth warning in logs');
});

// =============================================================================
// REQ-A09: Environment Variable Updates
// =============================================================================
describe('REQ-A09: Environment Variable Updates', () => {
  it('T-A29: .env.example contains FRONTEND_MODE', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains FRONTEND_MODE
    const envFile = readEnvExample();
    expect(envFile).toMatch(/FRONTEND_MODE/);
  });

  it('T-A30: FRONTEND_MODE default is static', () => {
    // GIVEN .env.example
    // WHEN the FRONTEND_MODE line is inspected
    // THEN its value is static
    const envFile = readEnvExample();
    expect(envFile).toMatch(/FRONTEND_MODE=static/);
  });

  it('T-A31: .env.example has comment explaining FRONTEND_MODE values', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN there is a comment near FRONTEND_MODE explaining valid values (dev/static)
    const envFile = readEnvExample();
    const lines = envFile.split('\n');
    const modeLineIdx = lines.findIndex((l) => l.includes('FRONTEND_MODE'));
    expect(modeLineIdx).toBeGreaterThanOrEqual(0);
    // Check for a comment on the same line or the line before
    const commentOnLine = lines[modeLineIdx].includes('#');
    const commentBefore = modeLineIdx > 0 && lines[modeLineIdx - 1].trim().startsWith('#');
    expect(
      commentOnLine || commentBefore,
      'FRONTEND_MODE should have an explanatory comment'
    ).toBe(true);
  });

  it('T-A32: existing variables are not removed from .env.example', () => {
    // GIVEN .env.example
    // WHEN compared to known existing variables
    // THEN none of the previously existing variables are removed
    const envFile = readEnvExample();
    // Sample of known variables from the base infrastructure (SPEC-20260407-001)
    const knownVars = [
      'REDIS_AUTH',
      'LANGFUSE_SECRET_KEY',
      'NEXTAUTH_SECRET',
      'SALT',
    ];
    for (const varName of knownVars) {
      expect(envFile, `${varName} should still be present`).toContain(varName);
    }
  });

  it('T-A09-CLICKHOUSE: .env.example contains CLICKHOUSE_PASSWORD=CHANGEME', () => {
    // GIVEN .env.example
    // WHEN inspected
    // THEN it contains CLICKHOUSE_PASSWORD=CHANGEME
    const envFile = readEnvExample();
    expect(envFile).toMatch(/CLICKHOUSE_PASSWORD=CHANGEME/);
  });
});
